name: Main
version: 1.0-SNAPSHOT
main: com.gameincluded.rflintstone.irl_interact.Main
api-version: 1.13
authors: [Ruben_Flinterman]
description: A plugin that connects to a weather API to change the weather in Minecraft
website: www.gameincluded.com
